### ISSUE TITLE
Add Phalcon

### ISSUE THREAD

**Issue by gnumoksha** [kocsismate/php-di-container-benchmarks#23]
Documentation for Phalcon's DI is on https://docs.phalconphp.com/en/latest/di

I think testing it will be a bit different because Phalcon is an extension and its DI is quite simple, however, it would be nice to compare Phalcon with other frameworks.

**Comment by kocsismate** [comment]
I am sorry to say that, but I wouldn't like to complicate the benchmark setup :/
