### ISSUE TITLE
RawGit has reached the end.

### ISSUE THREAD

**Issue by sasezaki** [kocsismate/php-di-container-benchmarks#34]
Hi.

https://rawgit.com/
> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
If you're currently using RawGit, please stop using it as soon as you can.

So, current benchmark HTML page should be moved to another service.

**Comment by kocsismate** [comment]
Hi,

Yes, I'm aware of the possible issue, however, I don't really want to do much about it, until it's absolutely necessary (when rawgit really stops working).

By the way, my plan is to render the results to a markdown format which can be directly displayed on GitHub. If you're willing to create a PR, I'll happily move the migration earlier. :)
