### ISSUE TITLE
chubbyphp/chubbyphp 1.3.1 should fix a performance issue

### ISSUE THREAD

**Issue by dominikzogg** [kocsismate/php-di-container-benchmarks#38]
Would be cool if you could rerun the benchmark. I seems my refactoring delegate some execution to DRY was a mistake in context of performance.

**Comment by kocsismate** [comment]
Yeah, sure. I'll run the benchmark again the same day when PHP 8.0 becomes GA (1 month from now). Please stay tuned :)

**Comment by kocsismate** [comment]
Done! :)
