### ISSUE TITLE
Add Auryn and correct info about Dice

### ISSUE THREAD

**Issue by garrettw** [kocsismate/php-di-container-benchmarks#5]
In [/var/benchmark.html](../blob/master/var/benchmark.html), you have Dice listed as not supporting autowiring when it actually does.

Also, I would like to see [Auryn](/rdlowrey/Auryn) included in the benchmark results -- I just want to know how it stacks up. 😉

**Comment by kocsismate** [comment]
I'll share the results of Auryn very soon! Thank you for enlightening me! :)

**Comment by kocsismate** [comment]
Done in my latest commit :)
