### ISSUE TITLE
Maybe put the results in the README?

### ISSUE THREAD

**Issue by dracony** [kocsismate/php-di-container-benchmarks#9]
It's pretty hard to find the results link on the first try. Perhaps a larger link or even results inside the readme itself would be more useful?

**Comment by kocsismate** [comment]
Good idea! When I first didn't find the results I decided to duplicate its link :) But I'll create a "Results" section instead.

Results in the readme would be nice too, but it would need manual steps each time a benchmark is run. So I'd rather avoid it.

**Comment by kocsismate** [comment]
Done! I hope you'll like it!

**Comment by dracony** [comment]
nice! thanks
